name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goversion:
          - 1.18
          - stable
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: go build -v -mod=readonly ./...
    - name: Test
      run: go test -v -check.v -race -mod=readonly ./...
    - name: Go vet
      run: go vet ./...
